using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Names
{
    public static string[] maleNames = new string[]
    {
        "Rhuhmud",
        "Fishun",
        "Gronken",
        "Stalvorn",
        "Glidrol",
        "Vif",
        "Blurbem",
        "Bror",
        "Butar-Zeoz",
        "Tinis",
        "Golmothet",
        "Shislar",
        "Jah",
        "Fuing",
        "Martascol",
        "Padrul",
        "Rheshen",
        "Bhadad",
        "Gankudd",
        "Tikvim",
        "Osaf",
        "Glon",
        "Orban",
        "Or",
        "Jeokem-Ze",
        "Raotheon",
        "Bremvenzask",
        "Monrit",
        "Wuy",
        "Croluele",
        "Zenrien",
        "Hahnin",
        "Nhumed",
        "Irstar",
        "Brecrork",
        "Argof",
        "Glil",
        "Volbarth",
        "Gavo-Nar",
        "Vethe",
        "Modjares",
        "Matvac",
        "Liuh",
        "Wiey",
        "Ainchueru",
        "Vuniz",
        "Fameim",
        "Nhuhnud",
        "Grandel",
        "Vuvolm",
        "Modof",
        "Nif",
        "Truldam",
        "Am",
        "Thojik-Veud",
        "Kumaf",
        "Bethounresk",
        "Goorvis",
        "Fiung",
        "Inrumuz",
        "Testue",
    };
    public static string[] femaleNames = new string[]
{
        "Valette",
        "Cohmuroh",
        "Nuseil",
        "Relirru",
        "Josvieh",
        "Sirles",
        "Vi",
        "Herhithro",
        "Kige",
        "Viresu",
        "Rizreth",
        "Eraldra",
        "Urse",
        "Xue",
        "Pai",
        "Quir",
        "Dartm",
        "Rotomah",
        "Jihneih",
        "Tachuzniell",
        "Lisrei",
        "Kinna",
        "Yas",
        "Ilgovay",
        "Mame",
        "Vosheza",
        "Sachi",
        "Thuvrarvis",
        "Lachu",
        "Yei",
        "Cao",
        "Ilq",
        "Nihlefel",
        "Cosuh",
        "Miezeiwo",
        "Cazu",
        "Mehna",
        "Vo",
        "Istrono",
        "Avo",
        "Nasufi",
        "Luzruth",
        "Hafuve",
        "Valdra",
        "Lia",
        "Lattv",
        "Luad",
};
    public static string[] surnames = new string[]
{
        " Bhossod",
        " Janno",
        " Flintblaze",
        " Rumblestrider",
        " Grusk",
        " Duzarsk",
        " Truewound",
        " Winterbrow",
        " Bekrizrud",
        " Luzifk",
        " Rugobyedye",
        " Vanunze",
        " Yung",
        " Xia",
        " Bodrese",
        " Pastuscen",
        " Nohlar",
        " Padein",
        " Greenshot",
        " Skullcut",
        " Sitsk",
        " Kevin",
        " Ironmaw",
        " Bloodoak",
        " Ronskupvot",
        " Fueltrekt",
        " Stomolzebe",
        " Zenungi",
        " Cein",
        " Wang",
        " Margargi",
        " Gunzurnas",
        " Hardroot",
        " Serpentchaser",
        " Emberbrew",
        " Stonesurge",
        " Caskleaf",
        " Hammerdrifter",
        " Deeptrapper",
        " Richforest",
        " Simpletail",
        " Brightthorne",
        " Peril",
        " Aliriou",
        " Chauzac",
        " Benie",
        " Angelet",
        " Verac",
        " Laurelon",
        " Brichachade",
        " Ravenrider",
        " Mildmantle",
        " Longtrapper",
        " Mourningmaul",
        " Willowflaw",
        " Graystriker",
        " Highcrag",
        " Greentaker",
        " Bloodblower",
        " Sterngleam",
        " Duret",
        " Vassegnes",
        " Croiseul",
        " Chanallac",
        " Cardaillet",
        " Bizezin",
        " Lauregre",
        " Montatillon",
        " Bougailot",
        " Meadowreaper",
        " Skybleeder",
        " Blazestrength",
        " Runewoods",
        " Evenvalor",
        " Forestwolf",
        " Cragthorn",
        " Silentkeep",
        " Lonefist",
        " Havenwood",
        " Entrone",
};
}
